name: FastAPI run 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        run:
          apt-get update && apt-get install -y python3 python3-pip
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.11.9'

      - name: Install Backend Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Start Backend Server
        run: uvicorn main:app --reload &
